// All game event types
export enum GameEventType {
  BATTLE_START = 'BATTLE_START',
  QUESTION_SHOW = 'QUESTION_SHOW',
  ANSWER_CORRECT = 'ANSWER_CORRECT',
  ANSWER_WRONG = 'ANSWER_WRONG',
  ATTACK_PLAYER = 'ATTACK_PLAYER',
  ATTACK_OPPONENT = 'ATTACK_OPPONENT',
  HP_CHANGED = 'HP_CHANGED',
  SHOW_EXPLANATION = 'SHOW_EXPLANATION',
  VICTORY = 'VICTORY',
  DEFEAT = 'DEFEAT',
}
